Ext.define("ExtMVC.model.central.Central",{
   extend:"Ext.data.Model",
   fields:[
       {
           name:"centralid",
           type:"int"
       },
       {
           name:"descripcion",
           type:"string"
       },
       {
            name:"idcoorcental",
            type:"integer"
        },
        {
            name:"coordinadora",
            type:"string"
        }
   ]
});